(require "lib/json" :as json)

(defn main []
  (let [n (json/j-num 42)
        s (json/j-str "hi")
        b (json/j-bool true)
        arr (let [e (vector)]
              (do (push e n) (push e s) (json/j-arr e)))
        pair (let [p (vector)] (do (push p "a") (push p n) p))
        pairs (let [ps (vector)] (do (push ps pair) ps))
        obj (json/j-obj pairs)
        sn (json/stringify n)
        ss (json/stringify s)
        sb (json/stringify b)
        sa (json/stringify arr)
        so (json/stringify obj)
        p1 (json/parse "123")
        p2 (json/parse "\"x\"")
        p3 (json/parse "[1,2]")
        p4 (json/parse "{\"k\":7}")
        p5 (json/parse "null")]
    (do (println sn)
        (println ss)
        (println sb)
        (println sa)
        (println so)
        (println (json/j-tag p1))
        (println (json/j-payload p1))
        (println (json/j-tag p2))
        (println (json/j-payload p2))
        (println (json/j-tag p3))
        (println (count (json/j-payload p3)))
        (println (json/j-tag p4))
        (println (json/j-payload (get (get (json/j-payload p4) 0) 1)))
        (println (json/j-tag p5))
        (println (json/stringify p4))
        0)))
