(require "lib/random" :as rng)
(require "lib/time" :as time)
(require "lib/regex" :as re)

(defn main []
  (let [t0 (time/now)
        tms (time/now-ms)
        _ (rng/seed! 12345)
        a (rng/rand-int 100)
        b (rng/rand-int 100)
        c (rng/rand-range 10 20)
        m1 (if (re/matches? "abc123" "[a-z]+[0-9]+") 1 0)
        m2 (if (re/matches? "abc" "[0-9]+") 1 0)
        f1 (re/find "xx42yy" "[0-9]+")
        f2 (re/find "hello" "[0-9]+")
        _2 (time/sleep-ms 1)
        el (time/elapsed-ms tms)]
    (do (println (if (> t0 1000000000) 1 0))
        (println (if (> tms 1000000000000) 1 0))
        (println a)
        (println b)
        (println (if (if (>= c 10) (<= c 20) false) 1 0))
        (println m1)
        (println m2)
        (println f1)
        (println f2)
        (println (if (>= el 0) 1 0))
        0)))
