;; Bars Doc generator — Phase 14.2
;; Extract public defn/defmacro and leading ;; comments → Markdown.
;;
;;   (require "compiler/doc.brs" :as doc)
;;   (doc/generate path src ast) → markdown string

(defn str-eq? [a b]
  (if (!= (count a) (count b)) false
    (= (str-starts-with? a b) 1)))

(defn ast-tag [x] (get x 0))
(defn ast-val [x] (get x 1))
(defn is-atom? [x] (< (ast-tag x) 1000))

(defn is-vec-form? [x]
  (if (is-atom? x) false
    (let [head (get x 0)]
      (if (is-atom? head) (= (ast-tag head) 28) false))))

(defn format-params [params]
  (if (is-vec-form? params)
    (let [n (count params)]
      (loop [i 1 acc "["]
        (if (>= i n)
          (str-concat acc "]")
          (let [p (get params i)
                name (if (if (is-atom? p) (= (ast-tag p) 1) false)
                       (ast-val p)
                       "?")
                piece (if (= i 1) name (str-concat " " name))]
            (recur (+ i 1) (str-concat acc piece))))))
    "[]"))

(defn form-offset [form]
  (if (is-atom? form)
    (if (>= (count form) 3) (get form 2) -1)
    (if (> (count form) 0)
      (form-offset (get form 0))
      -1)))

;; Find start index of the line containing byte off.
(defn line-start-at [src off]
  (loop [i off]
    (if (<= i 0) 0
      (if (= (str-get src (- i 1)) 10) i
        (recur (- i 1))))))

;; Is line (without trailing newline) a ;; doc comment?
(defn doc-line? [line]
  (if (< (count line) 2) false
    (if (= (str-get line 0) 59)
      (= (str-get line 1) 59)
      false)))

(defn strip-doc-prefix [line]
  (if (if (> (count line) 2) (= (str-get line 2) 32) false)
    (str-slice line 3 (count line))
    (str-slice line 2 (count line))))

;; Collect consecutive ;; lines immediately above form offset.
(defn comments-before [src off]
  (if (<= off 0) ""
    (let [ls (line-start-at src off)]
      (loop [pos ls acc ""]
        (if (<= pos 0) acc
          (let [prev-ls (line-start-at src (- pos 1))
                line (str-slice src prev-ls (- pos 1))]
            (if (doc-line? line)
              (let [text (strip-doc-prefix line)
                    next-acc (if (= (count acc) 0) text
                               (str-concat text (str-concat "\n" acc)))]
                (recur prev-ls next-acc))
              acc)))))))

;; Markdown inline code uses backticks (char 96).
(defn bt [] (code-char 96))

(defn md-code [s]
  (str-concat (bt) (str-concat s (bt))))

;; Inline docstring: first body expr is a string (with more body after).
(defn inline-docstring [form]
  (let [n (count form)]
    (if (< n 5) ""
      (let [b0 (get form 3)]
        (if (if (is-atom? b0) (= (ast-tag b0) 2) false)
          (ast-val b0)
          "")))))

(defn defn-entry [path src form kind]
  (let [n (count form)]
    (if (< n 3) ""
      (let [name-a (get form 1)
            params (get form 2)
            name (if (is-atom? name-a) (ast-val name-a) "?")
            sig (str-concat "("
                  (str-concat name
                    (str-concat " " (str-concat (format-params params) ")"))))
            off (form-offset form)
            cdoc (if (< off 0) "" (comments-before src off))
            idoc (inline-docstring form)
            docstr (if (> (count idoc) 0) idoc cdoc)
            h (str-concat "### " (str-concat (md-code name) "\n\n"))
            body (str-concat "**"
                    (str-concat kind
                      (str-concat "** "
                        (str-concat (md-code sig) "\n\n"))))
            md (str-concat h body)]
        (if (> (count docstr) 0)
          (str-concat md (str-concat docstr "\n\n"))
          (str-concat md "\n"))))))

(defn generate [path src ast]
  (let [n (count ast)
        header (str-concat "# "
                  (str-concat path "\n\nGenerated by bars-self doc.\n\n"))]
    (loop [i 0 acc header]
      (if (>= i n) acc
        (let [form (get ast i)
              piece
                (if (is-atom? form) ""
                  (let [h (get form 0)]
                    (if (is-atom? h)
                      (let [t (ast-tag h)]
                        (if (= t 10) (defn-entry path src form "function")
                          (if (= t 21) (defn-entry path src form "macro")
                            "")))
                      "")))]
          (recur (+ i 1) (str-concat acc piece)))))))
