;; Bars Type Inference — Stage 5 of self-hosting
;; Hindley-Milner type inference (simplified)
;; Generated by tools/gen_types.py — paren balance guaranteed.

;; ====== Type Representation ======
;; Type tags (internal): 0=I64, 1=F64, 2=Bool, 3=Void, 4=Str, 5=Var, 6=Fun, 7=Named

(defn t0 [tag]
  (let [v (vector)] (do (push v tag) v))
)


(defn T_I64 []
  (let [v (vector)] (do (push v 0) v))
)

(defn T_F64 []
  (let [v (vector)] (do (push v 1) v))
)

(defn T_Bool []
  (let [v (vector)] (do (push v 2) v))
)

(defn T_Void []
  (let [v (vector)] (do (push v 3) v))
)

(defn T_Str []
  (let [v (vector)] (do (push v 4) v))
)

(defn T_Var [id]
  (let [v (vector)] (do (push v 5) (do (push v id) v)))
)

(defn T_Fun [params ret]
  (let [v (vector)] (do (push v 6) (do (push v params) (do (push v ret) v))))
)

(defn T_Named [name]
  (let [v (vector)] (do (push v 7) (do (push v name) v)))
)

(defn type_tag [t]
  (get t 0)
)

(defn is_var? [t]
  (= (type_tag t) 5)
)

(defn is_fun? [t]
  (= (type_tag t) 6)
)

(defn var_id [t]
  (get t 1)
)

(defn fun_params [t]
  (get t 1)
)

(defn fun_ret [t]
  (get t 2)
)

(defn named_name [t]
  (get t 1)
)

(defn type_eq? [a b]
  (if (not (= (type_tag a) (type_tag b)))
    false
    (if (is_var? a)
      (= (var_id a) (var_id b))
      (if (is_fun? a)
        (if (= (count (fun_params a)) (count (fun_params b)))
          (loop [i 0]
            (if (>= i (count (fun_params a)))
              true
              (if true
                (recur (+ i 1))
                false)))
          false)
        true)))
)

(defn type_str [t]
  (if (is_var? t) "<var>"
    (if (is_fun? t) "<fn>"
      (let [tag (type_tag t)]
        (cond
          (= tag 0) "i64"
          (= tag 1) "f64"
          (= tag 2) "bool"
          (= tag 3) "void"
          (= tag 4) "str"
          (= tag 7) (named_name t)
          :else    "<?>")
  )))
)

;; ====== Environment ======

(defn str-eq? [a b]
  (if (!= (count a) (count b)) false
    (= (str-starts-with? a b) 1)))

;; Not-found = empty vector (count 0). Found = scheme [vars ty].
(defn env_lookup [env name]
  (loop [i 0]
    (if (>= i (count env)) (vector)
      (let [pair (get env i)]
        (if (str-eq? (get pair 0) name)
          (get pair 1)
          (recur (+ i 1))))))
)

(defn env_insert [env name scheme]
  (let [pair (vector)]
    (do (push pair name) (do (push pair scheme) (do (push env pair) env))))
)

;; ====== Substitution ======

(defn subst_get [subst id]
  (loop [i 0]
    (if (>= i (count subst)) (vector)
      (let [pair (get subst i)]
        (if (= (get pair 0) id)
          (get pair 1)
          (recur (+ i 1))))))
)

(defn subst_insert [subst id ty]
  (let [pair (vector)]
    (do (push pair id) (do (push pair ty) (do (push subst pair) subst))))
)

(defn apply_subst [subst ty]
  (loop [ty ty]
    (if (is_var? ty)
      (let [found (subst_get subst (var_id ty))]
        (if (> (count found) 0)
          (recur found)
          ty))
      (if (is_fun? ty)
        (let [ps (fun_params ty)
              nps (loop [i 0 acc (vector)]
                    (if (>= i (count ps)) acc
                      (do (push acc (get ps i)) (recur (+ i 1) acc))))]
          (T_Fun nps (fun_ret ty)))
        ty))
  )
)

;; ====== Unification ======

(defn normalize [ty subst]
  (loop [ty ty]
    (if (is_var? ty)
      (let [found (subst_get subst (var_id ty))]
        (if (> (count found) 0)
          (recur found)
          ty))
        ty))
)

(defn occurs? [vid ty subst]
  (let [ty (normalize ty subst)]
    (if (is_var? ty)
      (= (var_id ty) vid)
      (if (is_fun? ty)
        (loop [i 0 ps (fun_params ty)]
          (if (>= i (count ps))
            (let [rr (normalize (fun_ret ty) subst)]
              (if (is_var? rr)
                (= (var_id rr) vid)
                false))
            (let [p (normalize (get ps i) subst)]
              (if (is_var? p)
                (if (= (var_id p) vid)
                  true
                  (recur (+ i 1) ps))
                (recur (+ i 1) ps)))))
        false)))
)

(defn unify [a b subst]
  (let [a (normalize a subst)
        b (normalize b subst)]
    (if (type_eq? a b)
      [true subst]
      (if (is_var? a)
        (if (occurs? (var_id a) b subst)
          [false subst]
          [true (subst_insert subst (var_id a) b)])
        (if (is_var? b)
          (if (occurs? (var_id b) a subst)
            [false subst]
            [true (subst_insert subst (var_id b) a)])
          (if (is_fun? a)
            (if (is_fun? b)
              (if (not (= (count (fun_params a)) (count (fun_params b))))
                [false subst]
                (loop [i 0 s subst]
                  (if (>= i (count (fun_params a)))
                    [true s]
                    (let [res [true s]]
                      (if (get res 0)
                        (recur (+ i 1) (get res 1))
                        [false subst])))))
              [false subst])
            [false subst])))))
)

;; ====== Free Variables ======

(defn ty_free_vars [ty]
  (if (is_var? ty)
    (let [v (vector)] (do (push v (var_id ty)) v))
    (if (is_fun? ty)
      (let [ps (fun_params ty)
            vars (vector)]
        (do (loop [i 0]
              (if (>= i (count ps)) 0
                (let [inner (vector)]
                  (do (loop [j 0]
                        (if (>= j (count inner)) 0
                          (do (push vars (get inner j)) (recur (+ j 1)))))
                      (recur (+ i 1))))))
            (let [ret-vars (vector)]
              (do (loop [j 0]
                    (if (>= j (count ret-vars)) 0
                      (do (push vars (get ret-vars j)) (recur (+ j 1)))))
                  vars))))
      (let [v (vector)] v)))
)

(defn vec_contains? [v x]
  (loop [i 0]
    (if (>= i (count v)) false
      (if (= (get v i) x) true
        (recur (+ i 1)))))
)

(defn vec_diff [from rem]
  (let [result (vector)]
    (do (loop [i 0]
          (if (>= i (count from)) 0
            (let [x (get from i)]
              (if (vec_contains? rem x) 0
                (do (push result x) 0))
              (recur (+ i 1)))))
        result))
)

(defn env_free_vars [env]
  (let [vars (vector)]
    (do (loop [i 0]
          (if (>= i (count env)) 0
            (let [scheme (get (get env i) 1)
                  ty (get scheme 1)
                  fv (ty_free_vars ty)]
              (do (loop [j 0]
                    (if (>= j (count fv)) 0
                      (do (push vars (get fv j)) (recur (+ j 1)))))
                  (recur (+ i 1))))))
        vars))
)

;; ====== Generalize / Instantiate ======

(defn generalize [env ty]
  (let [ty-vars (ty_free_vars ty)
        env-vars (env_free_vars env)
        gen-vars (vec_diff ty-vars env-vars)]
    (let [v (vector)] (do (push v gen-vars) (do (push v ty) v))))
)

(defn mono_scheme [ty]
  (let [v (vector)] (do (push v (vector)) (do (push v ty) v)))
)

(defn instantiate [scheme counter]
  (let [vars (get scheme 0)
        ty (get scheme 1)
        subst (vector)]
    (do (loop [i 0]
          (if (>= i (count vars)) 0
            (let [id (get vars i)
                  new-var (T_Var (+ counter i))]
              (do (subst_insert subst id new-var) (recur (+ i 1))))))
        (apply_subst subst ty)))
)

;; ====== Inference Context ======

(defn set_at [v idx val]
  (loop [i 0 acc (vector)]
    (if (>= i (count v)) acc
      (if (= i idx)
        (do (push acc val) (recur (+ i 1) acc))
        (do (push acc (get v i)) (recur (+ i 1) acc)))))
)


;; ctx = [counter-vec, constraints-vec]
;; counter id = (count counter-vec); push mutates in place.
(defn fresh_var [ctx]
  (let [counter (get ctx 0)
        id (count counter)]
    (do (push counter 0)
        (T_Var id)))
)

(defn make_ctx []
  (let [v (vector)]
    (do (push v (vector))
        (push v (vector))
        v))
)

(defn ctx_add_constraint [ctx a b]
  (let [c (vector)
        cs (get ctx 1)]
    (do (push c a)
        (push c b)
        (push cs c)
        ctx))
)

;; ====== Builtin Environment ======

(defn i64_vec [] (let [v (vector)] (do (push v (T_I64)) v)))
(defn i64_i64 [] (let [v (vector)] (do (push v (T_I64)) (do (push v (T_I64)) v))))
(defn i64_i64-i64 [] (let [v (vector)] (do (push v (T_I64)) (do (push v (T_I64)) (do (push v (T_I64)) v)))))
(defn bool_vec [] (let [v (vector)] (do (push v (T_Bool)) v)))
(defn empty_vec [] (vector))

(defn builtin_env [ctx]
  (let [arith (mono_scheme (T_Fun (i64_i64) (T_I64)))
        cmp   (mono_scheme (T_Fun (i64_i64) (T_Bool)))
        unary (mono_scheme (T_Fun (i64_vec) (T_I64)))
        unary-bool (mono_scheme (T_Fun (i64_vec) (T_Bool)))
        bin   (mono_scheme (T_Fun (i64_i64) (T_I64)))
        i64-t (mono_scheme (T_I64))
        void-fn (mono_scheme (T_Fun (empty_vec) (T_Void)))
        slice3 (mono_scheme (T_Fun (i64_i64-i64) (T_I64)))
        env (vector)]
    (do (env_insert env "+" arith)
        (env_insert env "-" arith)
        (env_insert env "*" arith)
        (env_insert env "/" arith)
        (env_insert env "%" arith)
        (env_insert env "max" arith)
        (env_insert env "min" arith)
        (env_insert env "=" cmp)
        (env_insert env "!=" cmp)
        (env_insert env "<" cmp)
        (env_insert env ">" cmp)
        (env_insert env "<=" cmp)
        (env_insert env ">=" cmp)
        (env_insert env "inc" unary)
        (env_insert env "dec" unary)
        (env_insert env "abs" unary)
        (env_insert env "factorial" unary)
        (env_insert env "fib" unary)
        (env_insert env "even?" unary-bool)
        (env_insert env "odd?" unary-bool)
        (env_insert env "zero?" unary-bool)
        (env_insert env "pos?" unary-bool)
        (env_insert env "neg?" unary-bool)
        (env_insert env "not" (mono_scheme (T_Fun (bool_vec) (T_Bool))))
        (env_insert env "println" unary)
        (env_insert env "print" unary)
        (env_insert env "print-str" unary)
        (env_insert env "str-concat" bin)
        (env_insert env "str-get" bin)
        (env_insert env "str-slice" slice3)
        (env_insert env "str-index-of" bin)
        (env_insert env "str-starts-with?" bin)
        (env_insert env "str-ends-with?" bin)
        (env_insert env "count" unary)
        (env_insert env "first" unary)
        (env_insert env "last" unary)
        (env_insert env "get" bin)
        (env_insert env "push" bin)
        (env_insert env "vector" (mono_scheme (T_Fun (empty_vec) (T_I64))))
        (env_insert env "slurp" unary)
        (env_insert env "spit" bin)
        (env_insert env "exit" void-fn)
        (env_insert env "bars_system" unary)
        (env_insert env "args-count" (mono_scheme (T_Fun (empty_vec) (T_I64))))
        (env_insert env "args-get" unary)
        (env_insert env "nil" i64-t)
        (env_insert env "true" (mono_scheme (T_Bool)))
        (env_insert env "false" (mono_scheme (T_Bool)))
        (env_insert env "map" (mono_scheme (T_Fun (empty_vec) (T_I64))))
        (env_insert env "map-set" (mono_scheme (T_Fun (i64_i64-i64) (T_I64))))
        (env_insert env "map-get" (mono_scheme (T_Fun (i64_i64) (T_I64))))
        (env_insert env "map-count" unary)
        (env_insert env "def" (mono_scheme (T_Fun (i64_i64) (T_I64))))
        ;; do removed from builtin — it's a special form
        env))
)

;; ====== AST Helpers ======

(defn ast_tag [x]
  (get x 0)
)

(defn ast_val [x]
  (get x 1)
)

;; Atoms: tag < 1000. Compounds: head is nested vector (pointer >= 1000 as i64).
(defn is_atom? [x]
  (< (ast_tag x) 1000)
)

(defn contains_tag? [v tag]
  (loop [i 0]
    (if (>= i (count v)) false
      (if (= (ast_tag (get v i)) tag) true
        (recur (+ i 1)))))
)

;; Soft error — do not abort the process (pipeline decides hard fail).
(defn type_error [msg]
  (do (println (str-concat "Type error: " msg)) (T_Void))
)

;; Unwrap vector marker [[28] ...] and skip ^meta (tag 26) params.
(defn unwrap_vec [v]
  (if (is_atom? v) v
    (let [head (get v 0)]
      (if (if (is_atom? head) (= (ast_tag head) 28) false)
        (let [n (count v) out (vector)]
          (do (loop [i 1]
                (if (>= i n) 0
                  (do (push out (get v i)) (recur (+ i 1)))))
              out))
        v))))

(defn normalize_params [params]
  (let [plain (unwrap_vec params)
        n (count plain)
        out (vector)]
    (do (loop [i 0]
          (if (>= i n) 0
            (let [p (get plain i)]
              (if (if (is_atom? p) (= (ast_tag p) 26) false)
                (recur (+ i 1))
                (do (if (if (is_atom? p) (= (ast_tag p) 1) false)
                      (push out p)
                      0)
                    (recur (+ i 1)))))))
        out)))

;; ====== INFER-EXPR (core recursive function) ======

;; infer_expr returns [type, ctx]
;; Handles: atoms (0=num, 1=sym, 2=str, 3=kw, 4=nil, 5=bool)
;;          special forms: 10=defn, 11=let, 12=if, 13=do, 14=loop, 15=recur
;;          regular lists: function calls
(defn infer_expr [env ctx expr]
  (if (is_atom? expr)
    (let [tag (ast_tag expr)]
      (cond
        (= tag 0) [(T_I64) ctx]
        (= tag 1) (let [name (ast_val expr)
                        found (env_lookup env name)]
                    (if (> (count found) 0)
                      [(apply_subst (vector) (get found 1)) ctx]
                      ;; Unknown free var — fresh (modules / forward refs)
                      [(fresh_var ctx) ctx]))
        (= tag 2) [(T_Str) ctx]
        (= tag 3) [(T_Str) ctx]
        (= tag 4) [(T_Void) ctx]
        (= tag 5) [(T_Bool) ctx]
        :else     [(fresh_var ctx) ctx]))
    (let [tag (ast_tag (get expr 0))]
      (cond
        (= tag 10) (let [name-sym (get expr 1)
                              name (ast_val name-sym)
                              params (normalize_params (get expr 2))
                              body (get expr 3)]
                          (do (loop [i 0]
                                (if (>= i (count params)) 0
                                  (let [p (get params i)
                                        pname (ast_val p)]
                                    (do (env_insert env pname (mono_scheme (fresh_var ctx)))
                                        (recur (+ i 1))))))
                              (let [param-tys (loop [i 0 acc (vector)]
                                                (if (>= i (count params)) acc
                                                  (let [found (env_lookup env (ast_val (get params i)))]
                                                    (if (> (count found) 0)
                                                      (do (push acc (get found 1)) (recur (+ i 1) acc))
                                                      (recur (+ i 1) acc)))))
                                    res (infer_expr env ctx body)
                                    body-ty (get res 0)
                                    ctx (get res 1)]
                                (let [fn-ty (T_Fun param-tys body-ty)]
                                  (do (env_insert env name (mono_scheme fn-ty))
                                      [(T_Void) ctx])))))
        (= tag 11) (infer_let env ctx expr)
        (= tag 12) (infer_if env ctx expr)
        (= tag 13) (infer_do env ctx expr)
        (= tag 14) (infer_loop env ctx expr)
        (= tag 15) (infer_recur env ctx expr)
        (= tag 17) (infer_match env ctx expr)
        (= tag 22) (infer_quote env ctx expr)
        :else      (infer_call env ctx expr))))
)

;; ====== Special Form Handlers ======

;; Bindings are flat: [name1 val1 name2 val2 ...] (after unwrap_vec)
(defn infer_flat_binds [env ctx binds body-start body-ast]
  (let [plain (unwrap_vec binds)
        n (count plain)
        nbody (count body-ast)]
    (loop [i 0 env env ctx ctx]
      (if (>= i n)
        (if (<= nbody (+ body-start 1))
          (infer_expr env ctx (get body-ast body-start))
          (loop [j body-start last-ty (T_Void) ctx ctx]
            (if (>= j nbody) [last-ty ctx]
              (let [res (infer_expr env ctx (get body-ast j))
                    ty (get res 0)
                    ctx (get res 1)]
                (recur (+ j 1) ty ctx)))))
        (let [name-atom (get plain i)
              val-expr (get plain (+ i 1))
              name (ast_val name-atom)
              res (infer_expr env ctx val-expr)
              val-ty (get res 0)
              ctx (get res 1)]
          (do (env_insert env name (mono_scheme val-ty))
              (recur (+ i 2) env ctx)))))))

(defn infer_let [env ctx expr]
  (infer_flat_binds env ctx (get expr 1) 2 expr)
)

(defn infer_if [env ctx expr]
  (let [cond-expr (get expr 1)
        then-expr (get expr 2)
        else-expr (get expr 3)
        res-cond (infer_expr env ctx cond-expr)
        cond-ty (get res-cond 0)
        ctx (get res-cond 1)
        res-then (infer_expr env ctx then-expr)
        then-ty (get res-then 0)
        ctx (get res-then 1)
        res-else (infer_expr env ctx else-expr)
        else-ty (get res-else 0)
        ctx (get res-else 1)]
    (do (ctx_add_constraint ctx cond-ty (T_Bool))
        (ctx_add_constraint ctx then-ty else-ty)
        [then-ty ctx]))
)

(defn infer_do [env ctx expr]
  (let [n (count expr)]
    (loop [i 1 last-ty (T_Void) ctx ctx]
      (if (>= i n) [last-ty ctx]
        (let [res (infer_expr env ctx (get expr i))
              ty (get res 0)
              ctx (get res 1)]
          (recur (+ i 1) ty ctx)))))
)

(defn infer_loop [env ctx expr]
  (infer_flat_binds env ctx (get expr 1) 2 expr)
)

(defn infer_recur [env ctx expr]
  (let [n (count expr)]
    (loop [i 1 ctx ctx]
      (if (>= i n) [(fresh_var ctx) ctx]
        (let [res (infer_expr env ctx (get expr i))
              ctx (get res 1)]
          (recur (+ i 1) ctx)))))
)

;; Match AST: [[17] scrut pat1 body1 pat2 body2 ...]
(defn infer_match [env ctx expr]
  (let [matched (get expr 1)
        n (count expr)
        res-mat (infer_expr env ctx matched)
        mat-ty (get res-mat 0)
        ctx (get res-mat 1)
        result-ty (fresh_var ctx)]
    (loop [i 2 ctx ctx]
      (if (>= i n) [result-ty ctx]
        (let [pattern (get expr i)
              body (get expr (+ i 1))]
          (do (infer_pattern pattern env ctx)
              (let [res (infer_expr env ctx body)
                    arm-ty (get res 0)
                    ctx (get res 1)]
                (do (ctx_add_constraint ctx result-ty arm-ty)
                    (recur (+ i 2) ctx))))))))
)

(defn infer_pattern [pattern env ctx]
  (if (is_atom? pattern)
    (let [tag (ast_tag pattern)]
      (if (= tag 1)
        (env_insert env (ast_val pattern) (mono_scheme (fresh_var ctx)))
        0))
    0)
)

(defn infer_quote [env ctx expr]
  [(T_Void) ctx]
)

;; ====== Function Call Inference ======

(defn infer_args [env ctx expr start ret-ty]
  (let [n (count expr)]
    (loop [i start ctx ctx]
      (if (>= i n) [ret-ty ctx]
        (let [res (infer_expr env ctx (get expr i))
              ctx (get res 1)]
          (recur (+ i 1) ctx))))))

(defn infer_call [env ctx expr]
  (let [head (get expr 0)
        n (count expr)]
    (if (if (is_atom? head) (= (ast_tag head) 1) false)
      (let [name (ast_val head)
            found (env_lookup env name)]
        (if (> (count found) 0)
          (let [fn-ty (get found 1)]
            (if (is_fun? fn-ty)
              (let [param-tys (fun_params fn-ty)
                    ret-ty (fun_ret fn-ty)]
                (loop [i 1 ctx ctx]
                  (if (>= i n) [ret-ty ctx]
                    (let [res (infer_expr env ctx (get expr i))
                          arg-ty (get res 0)
                          ctx (get res 1)
                          param-idx (- i 1)]
                      (do (if (< param-idx (count param-tys))
                            (ctx_add_constraint ctx arg-ty (get param-tys param-idx))
                            0)
                          (recur (+ i 1) ctx))))))
              (infer_args env ctx expr 1 (fresh_var ctx))))
          (infer_args env ctx expr 1 (fresh_var ctx))))
      (let [res (infer_expr env ctx head)
            ctx (get res 1)]
        (infer_args env ctx expr 1 (fresh_var ctx))))))

;; ====== Solving Constraints ======

(defn solve [ctx]
  (let [subst (vector)
        constraints (get ctx 1)]
    (loop [i 0 subst subst failed 0]
      (if (>= i (count constraints))
        (if (= failed 0) [true subst] [false subst])
        (let [c (get constraints i)
              a (get c 0)
              b (get c 1)
              res (unify a b subst)]
          (if (get res 0)
            (recur (+ i 1) (get res 1) failed)
            (let [err (str-concat "type mismatch: " (str-concat (type_str a) (str-concat " vs " (type_str b))))]
              (do (println (str-concat "Type warning: " err))
                  (recur (+ i 1) subst 1))))))))
)

;; ====== Top-Level Inference ======

(defn infer_program [ast-list]
  (let [ctx (make_ctx)
        env (builtin_env ctx)]
    (loop [i 0 env env ctx ctx]
      (if (>= i (count ast-list))
        (solve ctx)
        (let [expr (get ast-list i)
              res (infer_expr env ctx expr)
              ty (get res 0)
              ctx (get res 1)]
          (recur (+ i 1) env ctx)))))
)

;; ====== Public API ======

;; Returns 0 on clean pass, 1 if any mismatch was reported.
;; Pipeline soft-fails by default; BARS_STRICT_TYPES=1 makes it hard-fail.
(defn type_check [ast-list]
  (let [result (infer_program ast-list)]
    (if (get result 0)
      0
      (do (println "Type check: issues found") 1)))
)


