;; Bars Type Inference — Stage 5 of self-hosting
;; Hindley-Milner type inference (simplified)
;; Generated by tools/gen_types.py — paren balance guaranteed.

;; ====== Type Representation ======
;; Type tags (internal): 0=I64, 1=F64, 2=Bool, 3=Void, 4=Str, 5=Var, 6=Fun, 7=Named

;; Flat push sequences (nested do/push miscompiles under Gen1→Gen2 LLVM).
(defn t0 [tag]
  (let [v (vector)]
    (do (push v tag) v)))

(defn T_I64 []
  (let [v (vector)]
    (do (push v 0) v)))

(defn T_F64 []
  (let [v (vector)]
    (do (push v 1) v)))

(defn T_Bool []
  (let [v (vector)]
    (do (push v 2) v)))

(defn T_Void []
  (let [v (vector)]
    (do (push v 3) v)))

(defn T_Str []
  (let [v (vector)]
    (do (push v 4) v)))

(defn T_Var [id]
  (let [v (vector)]
    (do (push v 5) (push v id) v)))

(defn T_Fun [params ret]
  (let [v (vector)]
    (do (push v 6) (push v params) (push v ret) v)))

(defn T_Named [name]
  (let [v (vector)]
    (do (push v 7) (push v name) v)))

(defn type_tag [t]
  (get t 0)
)

(defn is_var? [t]
  (= (type_tag t) 5)
)

(defn is_fun? [t]
  (= (type_tag t) 6)
)

(defn var_id [t]
  (get t 1)
)

(defn fun_params [t]
  (get t 1)
)

(defn fun_ret [t]
  (get t 2)
)

(defn named_name [t]
  (get t 1)
)

(defn type_eq? [a b]
  (if (not (= (type_tag a) (type_tag b)))
    false
    (if (is_var? a)
      (= (var_id a) (var_id b))
      (if (is_fun? a)
        (if (not (= (count (fun_params a)) (count (fun_params b))))
          false
          (if (not (type_eq? (fun_ret a) (fun_ret b)))
            false
            (loop [i 0]
              (if (>= i (count (fun_params a)))
                true
                (if (type_eq? (get (fun_params a) i) (get (fun_params b) i))
                  (recur (+ i 1))
                  false)))))
        (if (= (type_tag a) 7)
          (str-eq? (named_name a) (named_name b))
          true))))
)

(defn type_str [t]
  (if (is_var? t) "<var>"
    (if (is_fun? t) "<fn>"
      (let [tag (type_tag t)]
        (cond
          (= tag 0) "i64"
          (= tag 1) "f64"
          (= tag 2) "bool"
          (= tag 3) "void"
          (= tag 4) "str"
          (= tag 7) (named_name t)
          :else    "<?>")
  )))
)

;; ====== Environment ======

(defn str-eq? [a b]
  (if (!= (count a) (count b)) false
    (= (str-starts-with? a b) 1)))

;; println/print accept any value (runtime prints i64/str/vector/map/…).
;; Their args get no type constraint — kills soft-warning noise (17.7).
(defn print-any-fn? [name]
  (if (str-eq? name "println") true
    (str-eq? name "print")))

;; = / != are polymorphic at runtime (i64, strings, bools, keys…); args
;; get no type constraint either (17.9 — kwargs/str-key idiom).
(defn eq-any-fn? [name]
  (if (str-eq? name "=") true
    (str-eq? name "!=")))

;; count is also polymorphic at runtime (vector/string/map length).
(defn count-any-fn? [name]
  (str-eq? name "count"))

;; Collection access is untyped in the runtime (vectors/maps hold anything):
;; args get no constraint and the result is a fresh var per call (17.9).
(defn coll-any-fn? [name]
  (if (str-eq? name "get") true
    (if (str-eq? name "first") true
      (if (str-eq? name "last") true
        (if (str-eq? name "push") true
          (if (str-eq? name "pop") true
            (if (str-eq? name "map-get") true
              (str-eq? name "map-set"))))))))

;; Ret type for accept-any builtins; empty vector when not one.
(defn any-fn-ret [name]
  (if (print-any-fn? name) (T_I64)
    (if (eq-any-fn? name) (T_Bool)
      (if (count-any-fn? name) (T_I64)
        (if (str-eq? name "map-contains?") (T_Bool)
          (vector))))))

;; [1 ret-ty] for accept-any / poly-coll builtins; [0] otherwise.
(defn any-call-ret [name ctx]
  (if (coll-any-fn? name)
    (let [r (vector)] (do (push r 1) (push r (fresh_var ctx)) r))
    (let [t (any-fn-ret name)]
      (if (> (count t) 0)
        (let [r (vector)] (do (push r 1) (push r t) r))
        (let [r (vector)] (do (push r 0) r))))))

;; Not-found = empty vector (count 0). Found = scheme [vars ty].
;; Scans from the END: the most recent binding wins (lexical shadowing).
(defn env_lookup [env name]
  (loop [i (- (count env) 1)]
    (if (< i 0) (vector)
      (let [pair (get env i)]
        (if (str-eq? (get pair 0) name)
          (get pair 1)
          (recur (- i 1))))))
)

(defn env_insert [env name scheme]
  (let [pair (vector)]
    (do (push pair name)
        (push pair scheme)
        (push env pair)
        env)))

;; ====== Substitution ======

(defn subst_get [subst id]
  (loop [i 0]
    (if (>= i (count subst)) (vector)
      (let [pair (get subst i)]
        (if (= (get pair 0) id)
          (get pair 1)
          (recur (+ i 1))))))
)

(defn subst_insert [subst id ty]
  (let [pair (vector)]
    (do (push pair id)
        (push pair ty)
        (push subst pair)
        subst)))

(defn apply_subst [subst ty]
  (loop [ty ty]
    (if (is_var? ty)
      (let [found (subst_get subst (var_id ty))]
        (if (> (count found) 0)
          (recur found)
          ty))
      (if (is_fun? ty)
        (let [ps (fun_params ty)
              n (count ps)
              nps (loop [i 0 acc (vector)]
                    (if (>= i n) acc
                      (do (push acc (apply_subst subst (get ps i))) (recur (+ i 1) acc))))]
          (T_Fun nps (apply_subst subst (fun_ret ty))))
        ty))
  )
)

;; ====== Unification ======

(defn normalize [ty subst]
  (loop [ty ty]
    (if (is_var? ty)
      (let [found (subst_get subst (var_id ty))]
        (if (> (count found) 0)
          (recur found)
          ty))
        ty))
)

(defn occurs? [vid ty subst]
  (let [ty (normalize ty subst)]
    (if (is_var? ty)
      (= (var_id ty) vid)
      (if (is_fun? ty)
        (loop [i 0 ps (fun_params ty)]
          (if (>= i (count ps))
            (let [rr (normalize (fun_ret ty) subst)]
              (if (is_var? rr)
                (= (var_id rr) vid)
                false))
            (let [p (normalize (get ps i) subst)]
              (if (is_var? p)
                (if (= (var_id p) vid)
                  true
                  (recur (+ i 1) ps))
                (recur (+ i 1) ps)))))
        false)))
)

(defn unify [a b subst]
  (let [a (normalize a subst)
        b (normalize b subst)]
    (if (type_eq? a b)
      [true subst]
      (if (is_var? a)
        (if (occurs? (var_id a) b subst)
          [false subst]
          [true (subst_insert subst (var_id a) b)])
        (if (is_var? b)
          (if (occurs? (var_id b) a subst)
            [false subst]
            [true (subst_insert subst (var_id b) a)])
          (if (if (is_fun? a) (is_fun? b) false)
            (if (not (= (count (fun_params a)) (count (fun_params b))))
              [false subst]
              (loop [i 0 s subst]
                (if (>= i (count (fun_params a)))
                  (unify (fun_ret a) (fun_ret b) s)
                  (let [res (unify (get (fun_params a) i) (get (fun_params b) i) s)]
                    (if (get res 0)
                      (recur (+ i 1) (get res 1))
                      [false subst])))))
            [false subst])))))
)

;; ====== Free Variables ======

(defn tyfv-into [ty acc]
  (if (is_var? ty)
    (if (vec_contains? acc (var_id ty)) acc
      (do (push acc (var_id ty)) acc))
    (if (is_fun? ty)
      (let [ps (fun_params ty)
            n (count ps)
            acc2 (loop [i 0 a acc]
                   (if (>= i n) a
                     (recur (+ i 1) (tyfv-into (get ps i) a))))]
        (tyfv-into (fun_ret ty) acc2))
      acc)))

;; vec_contains? is defined below; calls resolve at emit time.
(defn ty_free_vars [ty]
  (tyfv-into ty (vector))
)

(defn vec_contains? [v x]
  (loop [i 0]
    (if (>= i (count v)) false
      (if (= (get v i) x) true
        (recur (+ i 1)))))
)

(defn vec_diff [from rem]
  (let [result (vector)]
    (do (loop [i 0]
          (if (>= i (count from)) 0
            (let [x (get from i)]
              (if (vec_contains? rem x) 0
                (do (push result x) 0))
              (recur (+ i 1)))))
        result))
)

(defn env_free_vars [env]
  (let [vars (vector)]
    (do (loop [i 0]
          (if (>= i (count env)) 0
            (let [scheme (get (get env i) 1)
                  ty (get scheme 1)
                  fv (ty_free_vars ty)]
              (do (loop [j 0]
                    (if (>= j (count fv)) 0
                      (do (push vars (get fv j)) (recur (+ j 1)))))
                  (recur (+ i 1))))))
        vars))
)

;; ====== Generalize / Instantiate ======

(defn generalize [env ty]
  (let [ty-vars (ty_free_vars ty)
        env-vars (env_free_vars env)
        gen-vars (vec_diff ty-vars env-vars)
        v (vector)]
    (do (push v gen-vars) (push v ty) v)))

(defn mono_scheme [ty]
  (let [v (vector)]
    (do (push v (vector)) (push v ty) v)))

;; Polymorphic identity scheme 'a -> 'a (one quantified var, id 100).
(defn id_scheme []
  (let [vs (vector)
        args (vector)
        s (vector)]
    (do (push vs 100)
        (push args (T_Var 100))
        (push s vs)
        (push s (T_Fun args (T_Var 100)))
        s)))

(defn instantiate [scheme counter]
  (let [vars (get scheme 0)
        ty (get scheme 1)
        subst (vector)]
    (do (loop [i 0]
          (if (>= i (count vars)) 0
            (let [id (get vars i)
                  new-var (T_Var (+ counter i))]
              (do (subst_insert subst id new-var) (recur (+ i 1))))))
        (apply_subst subst ty)))
)

;; Instantiate with fresh vars drawn from ctx (17.8). Reserves counter ids.
(defn instantiate_ctx [scheme ctx]
  (let [vars (get scheme 0)
        n (count vars)
        counter (get ctx 0)
        base (count counter)]
    (do (loop [i 0]
          (if (>= i n) 0
            (do (push counter 0) (recur (+ i 1)))))
        (instantiate scheme base)))
)

;; Free vars of the first n env entries (snapshot before defn params).
(defn env_free_vars_prefix [env n]
  (let [vars (vector)]
    (do (loop [i 0]
          (if (>= i n) 0
            (let [scheme (get (get env i) 1)
                  ty (get scheme 1)
                  fv (ty_free_vars ty)]
              (do (loop [j 0]
                    (if (>= j (count fv)) 0
                      (do (push vars (get fv j)) (recur (+ j 1)))))
                  (recur (+ i 1))))))
        vars))
)

;; Generalize against the env prefix [0, n) — defn params/locals excluded.
(defn generalize_prefix [env n ty]
  (let [ty-vars (ty_free_vars ty)
        env-vars (env_free_vars_prefix env n)
        gen-vars (vec_diff ty-vars env-vars)
        v (vector)]
    (do (push v gen-vars) (push v ty) v)))

;; ====== Inference Context ======

(defn set_at [v idx val]
  (loop [i 0 acc (vector)]
    (if (>= i (count v)) acc
      (if (= i idx)
        (do (push acc val) (recur (+ i 1) acc))
        (do (push acc (get v i)) (recur (+ i 1) acc)))))
)


;; ctx = [counter-vec, constraints-vec]
;; counter id = (count counter-vec); push mutates in place.
(defn fresh_var [ctx]
  (let [counter (get ctx 0)
        id (count counter)]
    (do (push counter 0)
        (T_Var id)))
)

;; ctx = [counter-vec, constraints-vec, path, source-text]
(defn make_ctx []
  (let [v (vector)]
    (do (push v (vector))
        (push v (vector))
        (push v "")
        (push v "")
        v))
)

(defn make_ctx_at [path text]
  (let [v (vector)]
    (do (push v (vector))
        (push v (vector))
        (push v path)
        (push v text)
        v))
)

(defn ctx_path [ctx]
  (if (>= (count ctx) 3) (get ctx 2) ""))

(defn ctx_text [ctx]
  (if (>= (count ctx) 4) (get ctx 3) ""))

;; Constraint is [type-a type-b offset] (offset -1 if unknown).
(defn ctx_add_constraint_at [ctx a b off]
  (let [c (vector)
        cs (get ctx 1)]
    (do (push c a)
        (push c b)
        (push c off)
        (push cs c)
        ctx))
)

(defn ctx_add_constraint [ctx a b]
  (ctx_add_constraint_at ctx a b -1)
)

;; ====== Builtin Environment ======

(defn i64_vec []
  (let [v (vector)]
    (do (push v (T_I64)) v)))

(defn i64_i64 []
  (let [v (vector)]
    (do (push v (T_I64)) (push v (T_I64)) v)))

(defn i64_i64-i64 []
  (let [v (vector)]
    (do (push v (T_I64)) (push v (T_I64)) (push v (T_I64)) v)))

(defn str_vec []
  (let [v (vector)]
    (do (push v (T_Str)) v)))

(defn str_str []
  (let [v (vector)]
    (do (push v (T_Str)) (push v (T_Str)) v)))

(defn str_i64 []
  (let [v (vector)]
    (do (push v (T_Str)) (push v (T_I64)) v)))

(defn i64_str []
  (let [v (vector)]
    (do (push v (T_I64)) (push v (T_Str)) v)))

(defn str_i64-i64 []
  (let [v (vector)]
    (do (push v (T_Str)) (push v (T_I64)) (push v (T_I64)) v)))

(defn str_str_str []
  (let [v (vector)]
    (do (push v (T_Str)) (push v (T_Str)) (push v (T_Str)) v)))

(defn bool_vec []
  (let [v (vector)]
    (do (push v (T_Bool)) v)))

(defn empty_vec [] (vector))

(defn builtin_env [ctx]
  (let [arith (mono_scheme (T_Fun (i64_i64) (T_I64)))
        cmp   (mono_scheme (T_Fun (i64_i64) (T_Bool)))
        unary (mono_scheme (T_Fun (i64_vec) (T_I64)))
        unary-bool (mono_scheme (T_Fun (i64_vec) (T_Bool)))
        bin   (mono_scheme (T_Fun (i64_i64) (T_I64)))
        i64-t (mono_scheme (T_I64))
        void-fn (mono_scheme (T_Fun (empty_vec) (T_Void)))
        ;; string-typed schemes (17.7 — less soft-warning noise)
        s2i   (mono_scheme (T_Fun (str_vec) (T_I64)))
        s2s   (mono_scheme (T_Fun (str_vec) (T_Str)))
        ss2s  (mono_scheme (T_Fun (str_str) (T_Str)))
        ss2i  (mono_scheme (T_Fun (str_str) (T_I64)))
        ss2b  (mono_scheme (T_Fun (str_str) (T_Bool)))
        si2i  (mono_scheme (T_Fun (str_i64) (T_I64)))
        is2i  (mono_scheme (T_Fun (i64_str) (T_I64)))
        is2s  (mono_scheme (T_Fun (i64_str) (T_Str)))
        ii2s  (mono_scheme (T_Fun (i64_i64) (T_Str)))
        i2s   (mono_scheme (T_Fun (i64_vec) (T_Str)))
        sii2s (mono_scheme (T_Fun (str_i64-i64) (T_Str)))
        sss2s (mono_scheme (T_Fun (str_str_str) (T_Str)))
        env (vector)]
    (do (env_insert env "+" arith)
        (env_insert env "-" arith)
        (env_insert env "*" arith)
        (env_insert env "/" arith)
        (env_insert env "%" arith)
        (env_insert env "max" arith)
        (env_insert env "min" arith)
        (env_insert env "=" cmp)
        (env_insert env "!=" cmp)
        (env_insert env "<" cmp)
        (env_insert env ">" cmp)
        (env_insert env "<=" cmp)
        (env_insert env ">=" cmp)
        (env_insert env "inc" unary)
        (env_insert env "dec" unary)
        (env_insert env "abs" unary)
        (env_insert env "factorial" unary)
        (env_insert env "fib" unary)
        (env_insert env "even?" unary-bool)
        (env_insert env "odd?" unary-bool)
        (env_insert env "zero?" unary-bool)
        (env_insert env "pos?" unary-bool)
        (env_insert env "neg?" unary-bool)
        (env_insert env "not" (mono_scheme (T_Fun (bool_vec) (T_Bool))))
        (env_insert env "println" unary)
        (env_insert env "print" unary)
        (env_insert env "print-str" s2i)
        (env_insert env "str-concat" ss2s)
        (env_insert env "str-count" s2i)
        (env_insert env "str-get" si2i)
        (env_insert env "str-slice" sii2s)
        (env_insert env "str-substring" sii2s)
        (env_insert env "str-trim" s2s)
        (env_insert env "str-index-of" ss2i)
        (env_insert env "str-replace" sss2s)
        (env_insert env "str-starts-with?" ss2b)
        (env_insert env "str-ends-with?" ss2b)
        (env_insert env "str-split" ss2i)
        (env_insert env "str-join" is2s)
        (env_insert env "char-code" s2i)
        (env_insert env "count" unary)
        (env_insert env "first" unary)
        (env_insert env "last" unary)
        (env_insert env "get" bin)
        (env_insert env "push" bin)
        (env_insert env "vector" (mono_scheme (T_Fun (empty_vec) (T_I64))))
        (env_insert env "slurp" s2s)
        (env_insert env "spit" ss2i)
        (env_insert env "exit" void-fn)
        (env_insert env "bars_system" s2i)
        (env_insert env "bars_env_is_set" s2i)
        (env_insert env "bars_getenv" s2s)
        (env_insert env "bars_file_mtime" s2i)
        (env_insert env "bars_sleep_ms" unary)
        (env_insert env "bars_file_exists" s2i)
        (env_insert env "bars_file_delete" s2i)
        (env_insert env "bars_file_append" ss2i)
        (env_insert env "bars_time_unix" (mono_scheme (T_Fun (empty_vec) (T_I64))))
        (env_insert env "bars_time_ms" (mono_scheme (T_Fun (empty_vec) (T_I64))))
        (env_insert env "bars_srand" unary)
        (env_insert env "bars_rand" (mono_scheme (T_Fun (empty_vec) (T_I64))))
        (env_insert env "bars_re_is_match" ss2i)
        (env_insert env "bars_re_find" ss2i)
        (env_insert env "bars_tcp_connect" si2i)
        (env_insert env "bars_tcp_listen" unary)
        (env_insert env "bars_tcp_accept" unary)
        (env_insert env "bars_tcp_send" is2i)
        (env_insert env "bars_tcp_recv" ii2s)
        (env_insert env "bars_tcp_close" unary)
        (env_insert env "bars_sha256" s2s)
        (env_insert env "str-from-i64" i2s)
        (env_insert env "code-char" i2s)
        (env_insert env "args-count" (mono_scheme (T_Fun (empty_vec) (T_I64))))
        (env_insert env "args-get" i2s)
        (env_insert env "nil" i64-t)
        (env_insert env "true" (mono_scheme (T_Bool)))
        (env_insert env "false" (mono_scheme (T_Bool)))
        (env_insert env "map" (mono_scheme (T_Fun (empty_vec) (T_I64))))
        (env_insert env "map-set" (mono_scheme (T_Fun (i64_i64-i64) (T_I64))))
        (env_insert env "map-get" (mono_scheme (T_Fun (i64_i64) (T_I64))))
        (env_insert env "map-count" unary)
        (env_insert env "map-contains?" cmp)
        (env_insert env "map-keys" unary)
        (env_insert env "map-values" unary)
        (env_insert env "set" (mono_scheme (T_Fun (empty_vec) (T_I64))))
        (env_insert env "set-add" bin)
        (env_insert env "set-contains?" cmp)
        (env_insert env "set-count" unary)
        (env_insert env "def" (id_scheme))
        ;; do removed from builtin — it's a special form
        env))
)

;; ====== AST Helpers ======

(defn ast_tag [x]
  (get x 0)
)

(defn ast_val [x]
  (get x 1)
)

;; Atoms: tag < 1000. Compounds: head is nested vector (pointer >= 1000 as i64).
(defn is_atom? [x]
  (< (ast_tag x) 1000)
)

(defn contains_tag? [v tag]
  (loop [i 0]
    (if (>= i (count v)) false
      (if (= (ast_tag (get v i)) tag) true
        (recur (+ i 1)))))
)

;; Soft error — do not abort the process (pipeline decides hard fail).
(defn type_error [msg]
  (do (println (str-concat "error: type: " msg)) (T_Void))
)

;; Optional source offset on atoms: [tag val off]
(defn ast_off [x]
  (if (>= (count x) 3) (get x 2) -1))

;; Best-effort offset for any expr (atom or head of list).
(defn expr_off [expr]
  (if (= expr 0) -1
    (if (is_atom? expr)
      (ast_off expr)
      (if (> (count expr) 0) (expr_off (get expr 0)) -1))))

(defn int-str [n] (str-from-i64 n))

(defn offset-to-span [text offset]
  (let [n (count text)
        lim (if (< offset 0) 0 (if (> offset n) n offset))]
    (loop [i 0 line 1 col 1]
      (if (>= i lim)
        (let [v (vector)]
          (do (push v line) (push v col) v))
        (if (= (str-get text i) 10)
          (recur (+ i 1) (+ line 1) 1)
          (recur (+ i 1) line (+ col 1)))))))

(defn line-content [text line-num]
  (let [n (count text)]
    (loop [i 0 cur 1 start 0]
      (if (>= i n)
        (if (= cur line-num) (str-slice text start n) "")
        (if (= (str-get text i) 10)
          (if (= cur line-num)
            (str-slice text start i)
            (recur (+ i 1) (+ cur 1) (+ i 1)))
          (recur (+ i 1) cur start))))))

(defn n-spaces [n]
  (loop [i 0 acc ""]
    (if (>= i n) acc
      (recur (+ i 1) (str-concat acc " ")))))

(defn print-snippet [text line col]
  (if (if (<= line 0) true (= (count text) 0))
    0
    (let [src (line-content text line)
          gutter (int-str line)
          pad (n-spaces (count gutter))
          c0 (if (< col 1) 0 (- col 1))
          c1 (if (> c0 (count src)) (count src) c0)
          indent (n-spaces c1)]
      (do (println "")
          (println (str-concat "  " (str-concat gutter (str-concat " | " src))))
          (println (str-concat "  " (str-concat pad (str-concat " | " (str-concat indent "^")))))
          0))))

(defn type_warn [msg path]
  (if (> (count path) 0)
    (println (str-concat "warning: type: " (str-concat msg (str-concat " [" (str-concat path "]")))))
    (println (str-concat "warning: type: " msg)))
)

;; Report type warning with optional line:col + snippet (when off is in text).
(defn type_warn_at [msg path text off]
  (let [tlen (count text)]
    (if (if (>= off 0) (< off tlen) false)
      (let [lc (offset-to-span text off)
            line (get lc 0)
            col (get lc 1)
            where (str-concat (int-str line) (str-concat ":" (int-str col)))]
        (do (println (str-concat "warning: type: " (str-concat msg (str-concat " at " where))))
            (if (> (count path) 0)
              (println (str-concat "  --> " (str-concat path (str-concat ":" where))))
              0)
            (print-snippet text line col)
            0))
      (type_warn msg path)))
)

;; Unwrap vector marker [[28] ...] and skip ^meta (tag 26) params.
(defn unwrap_vec [v]
  (if (is_atom? v) v
    (let [head (get v 0)]
      (if (if (is_atom? head) (= (ast_tag head) 28) false)
        (let [n (count v) out (vector)]
          (do (loop [i 1]
                (if (>= i n) 0
                  (do (push out (get v i)) (recur (+ i 1)))))
              out))
        v))))

(defn normalize_params [params]
  (let [plain (unwrap_vec params)
        n (count plain)
        out (vector)]
    (do (loop [i 0]
          (if (>= i n) 0
            (let [p (get plain i)]
              (if (if (is_atom? p) (= (ast_tag p) 26) false)
                (recur (+ i 1))
                (do (if (if (is_atom? p) (= (ast_tag p) 1) false)
                      (push out p)
                      0)
                    (recur (+ i 1)))))))
        out)))

;; ====== INFER-EXPR ======
;; Returns [type, ctx]. ctx is mutated in place (constraints/counter);
;; always pass the same ctx — never rebind from (get res 1) in loops
;; (Gen1 LLVM leaves uninit allocas on sibling branches for loop rebinds).

(defn ret2 [ty ctx]
  (let [v (vector)]
    (do (push v ty) (push v ctx) v)))

(defn res-ty [r] (get r 0))

(defn infer_expr [env ctx expr]
  (if (is_atom? expr)
    (let [tag (ast_tag expr)]
      (if (= tag 0) (ret2 (T_I64) ctx)
        (if (= tag 1)
          (let [name (ast_val expr)
                found (env_lookup env name)]
            (if (> (count found) 0)
              (ret2 (instantiate_ctx found ctx) ctx)
              (ret2 (fresh_var ctx) ctx)))
          (if (= tag 2) (ret2 (T_Str) ctx)
            (if (= tag 3) (ret2 (T_Str) ctx)
              (if (= tag 4) (ret2 (T_Void) ctx)
                (if (= tag 5) (ret2 (T_Bool) ctx)
                  (ret2 (fresh_var ctx) ctx))))))))
    (let [tag (ast_tag (get expr 0))]
      (if (= tag 10)
        (let [name (ast_val (get expr 1))
              params (normalize_params (get expr 2))
              body (get expr 3)
              outer-n (count env)]
          (do (loop [i 0]
                (if (>= i (count params)) 0
                  (do (env_insert env (ast_val (get params i)) (mono_scheme (fresh_var ctx)))
                      (recur (+ i 1)))))
              (let [param-tys (vector)
                    _ (loop [i 0]
                        (if (>= i (count params)) 0
                          (let [found (env_lookup env (ast_val (get params i)))]
                            (do (if (> (count found) 0)
                                  (push param-tys (get found 1))
                                  0)
                                (recur (+ i 1))))))
                    body-ty (res-ty (infer_expr env ctx body))
                    fn-ty (T_Fun param-tys body-ty)]
                (do (env_insert env name (generalize_prefix env outer-n fn-ty))
                    (ret2 (T_Void) ctx)))))
        (if (= tag 11) (infer_let env ctx expr)
          (if (= tag 12) (infer_if env ctx expr)
            (if (= tag 13) (infer_do env ctx expr)
              (if (= tag 14) (infer_loop env ctx expr)
                (if (= tag 15) (infer_recur env ctx expr)
                  (if (= tag 17) (infer_match env ctx expr)
                    (if (= tag 22) (infer_quote env ctx expr)
                      (infer_call env ctx expr))))))))))))

;; ====== Special Form Handlers ======

(defn infer_flat_binds [env ctx binds body-start body-ast]
  (let [plain (unwrap_vec binds)
        n (count plain)
        nbody (count body-ast)]
    (loop [i 0]
      (if (>= i n)
        (if (<= nbody (+ body-start 1))
          (infer_expr env ctx (get body-ast body-start))
          (loop [j body-start last-ty (T_Void)]
            (if (>= j nbody) (ret2 last-ty ctx)
              (let [ty (res-ty (infer_expr env ctx (get body-ast j)))]
                (recur (+ j 1) ty)))))
        (let [name (ast_val (get plain i))
              val-ty (res-ty (infer_expr env ctx (get plain (+ i 1))))]
          (do (env_insert env name (mono_scheme val-ty))
              (recur (+ i 2))))))))

(defn infer_let [env ctx expr]
  (infer_flat_binds env ctx (get expr 1) 2 expr))

(defn infer_if [env ctx expr]
  (let [cond-e (get expr 1)
        then-e (get expr 2)
        else-e (get expr 3)
        cond-ty (res-ty (infer_expr env ctx cond-e))
        then-ty (res-ty (infer_expr env ctx then-e))
        else-ty (res-ty (infer_expr env ctx else-e))]
    (do (ctx_add_constraint_at ctx cond-ty (T_Bool) (expr_off cond-e))
        (ctx_add_constraint_at ctx then-ty else-ty (expr_off then-e))
        (ret2 then-ty ctx))))

(defn infer_do [env ctx expr]
  (let [n (count expr)]
    (loop [i 1 last-ty (T_Void)]
      (if (>= i n) (ret2 last-ty ctx)
        (recur (+ i 1) (res-ty (infer_expr env ctx (get expr i))))))))

(defn infer_loop [env ctx expr]
  (infer_flat_binds env ctx (get expr 1) 2 expr))

(defn infer_recur [env ctx expr]
  (let [n (count expr)]
    (do (loop [i 1]
          (if (>= i n) 0
            (do (infer_expr env ctx (get expr i))
                (recur (+ i 1)))))
        (ret2 (fresh_var ctx) ctx))))

(defn infer_match [env ctx expr]
  (let [n (count expr)
        _ (infer_expr env ctx (get expr 1))
        result-ty (fresh_var ctx)]
    (do (loop [i 2]
          (if (>= i n) 0
            (do (infer_pattern (get expr i) env ctx)
                (let [arm-e (get expr (+ i 1))
                      arm-ty (res-ty (infer_expr env ctx arm-e))]
                  (do (ctx_add_constraint_at ctx result-ty arm-ty (expr_off arm-e))
                      (recur (+ i 2)))))))
        (ret2 result-ty ctx))))

(defn infer_pattern [pattern env ctx]
  (if (is_atom? pattern)
    (if (= (ast_tag pattern) 1)
      (env_insert env (ast_val pattern) (mono_scheme (fresh_var ctx)))
      0)
    0))

(defn infer_quote [env ctx expr]
  (ret2 (T_Void) ctx))

;; ====== Function Call Inference ======

(defn infer_args [env ctx expr start ret-ty]
  (let [n (count expr)]
    (do (loop [i start]
          (if (>= i n) 0
            (do (infer_expr env ctx (get expr i))
                (recur (+ i 1)))))
        (ret2 ret-ty ctx))))

(defn infer_call [env ctx expr]
  (let [head (get expr 0)
        n (count expr)]
    (if (if (is_atom? head) (= (ast_tag head) 1) false)
      (let [name (ast_val head)
            found (env_lookup env name)
            anyr (any-call-ret name ctx)]
        (if (= (get anyr 0) 1)
          (infer_args env ctx expr 1 (get anyr 1))
        (if (> (count found) 0)
          (let [fn-ty (instantiate_ctx found ctx)]
            (if (is_fun? fn-ty)
              (let [param-tys (fun_params fn-ty)
                    ret-ty (fun_ret fn-ty)]
                (do (loop [i 1]
                      (if (>= i n) 0
                        (let [arg-e (get expr i)
                              arg-ty (res-ty (infer_expr env ctx arg-e))
                              param-idx (- i 1)]
                          (do (if (< param-idx (count param-tys))
                                (ctx_add_constraint_at ctx arg-ty (get param-tys param-idx) (expr_off arg-e))
                                0)
                              (recur (+ i 1))))))
                    (ret2 ret-ty ctx)))
              (infer_args env ctx expr 1 (fresh_var ctx))))
          (infer_args env ctx expr 1 (fresh_var ctx)))))
      (do (infer_expr env ctx head)
          (infer_args env ctx expr 1 (fresh_var ctx))))))
;; ====== Solving Constraints ======

;; Solve constraints [start, end) with a fresh subst; warn on each failure.
(defn solve_from [ctx start]
  (let [subst (vector)
        constraints (get ctx 1)
        path (ctx_path ctx)
        text (ctx_text ctx)]
    (loop [i start subst subst failed 0]
      (if (>= i (count constraints))
        (if (= failed 0) [true subst] [false subst])
        (let [c (get constraints i)
              a (get c 0)
              b (get c 1)
              off (if (>= (count c) 3) (get c 2) -1)
              res (unify a b subst)]
          (if (get res 0)
            (recur (+ i 1) (get res 1) failed)
            (let [err (str-concat "type mismatch: " (str-concat (type_str a) (str-concat " vs " (type_str b))))]
              (do (type_warn_at err path text off)
                  (recur (+ i 1) subst 1))))))))
)

(defn solve [ctx]
  (solve_from ctx 0)
)

;; Apply subst to env entries added at/after `start` (17.9 interleaved solve).
;; Makes defn schemes concrete after their body's constraints are solved.
(defn env_apply_subst_from [env start subst]
  (loop [i start env env]
    (if (>= i (count env)) env
      (let [pair (get env i)
            scheme (get pair 1)
            new-ty (apply_subst subst (get scheme 1))
            new-scheme (vector)
            _ (do (push new-scheme (get scheme 0)) (push new-scheme new-ty))
            new-pair (vector)
            _ (do (push new-pair (get pair 0)) (push new-pair new-scheme))]
        (recur (+ i 1) (set_at env i new-pair)))))
)

;; ====== Top-Level Inference ======

;; Interleaved: after each top-level form, solve its constraints and apply
;; the subst to the env entries it added (17.9). Cross-form pinning is then
;; impossible and stored defn schemes are concrete (true call-site errors).
(defn infer_program_at [ast-list path text]
  (let [ctx (make_ctx_at path text)
        env (builtin_env ctx)]
    (loop [i 0 env env failed 0 solved 0]
      (if (>= i (count ast-list))
        (if (= failed 0) [true (vector)] [false (vector)])
        (let [expr (get ast-list i)
              env-n (count env)
              res (infer_expr env ctx expr)
              n-now (count (get ctx 1))
              sres (solve_from ctx solved)
              subst (get sres 1)
              env2 (env_apply_subst_from env env-n subst)
              f2 (if (get sres 0) failed 1)]
          (recur (+ i 1) env2 f2 n-now)))))
)

(defn infer_program [ast-list]
  (infer_program_at ast-list "" "")
)

;; ====== Public API ======

;; Returns 0 on clean pass, 1 if any mismatch was reported.
;; Pipeline soft-fails by default; BARS_STRICT_TYPES=1 makes it hard-fail.
(defn type_check_at [ast-list path text]
  (let [result (infer_program_at ast-list path text)]
    (if (get result 0)
      0
      (do (type_warn "check reported issues" path) 1)))
)

(defn type_check [ast-list]
  (type_check_at ast-list "" "")
)

