# AI-First REPL for Bara Lang
import os, osproc, strutils, json, times, net
import reader, emitter, types, macros, eval, ai_assist

type
  ReplMode* = enum
    rmHuman, rmJson, rmEdn

  ReplState* = object
    mode*: ReplMode
    ns*: string
    defs*: seq[CljVal]
    tempDir*: string
    sessionId*: string
    libPath*: string
    evalEnv*: Env

proc getLibPath(): string =
  # Check environment variable first
  let envPath = getEnv("CLJNIM_LIB_PATH", "")
  if envPath.len > 0 and dirExists(envPath):
    return envPath
  # Check current directory's lib first (project-local libs)
  let candidate0 = getCurrentDir() / "lib"
  if dirExists(candidate0): return candidate0
  let appDir = getAppDir()
  let candidate1 = appDir / "lib"
  let candidate2 = appDir.parentDir / "lib"
  if dirExists(candidate1): return candidate1
  if dirExists(candidate2): return candidate2
  return "lib"

proc initReplState*(mode: ReplMode): ReplState =
  initBuiltinMacros()
  result.mode = mode
  result.ns = "user"
  result.defs = @[]
  result.tempDir = getTempDir() / "cljnim_repl_" & $getCurrentProcessId()
  createDir(result.tempDir)
  result.sessionId = $getCurrentProcessId() & "_" & $epochTime().int
  result.libPath = getLibPath()
  result.evalEnv = newTopLevelEnv()

proc cleanup*(state: ReplState) =
  try:
    removeDir(state.tempDir)
  except:
    discard

proc cljReprLocal(v: CljVal): string =
  if v.isNil: return "nil"
  case v.kind
  of ckNil: result = "nil"
  of ckBool:
    if v.boolVal: result = "true"
    else: result = "false"
  of ckInt: result = $v.intVal
  of ckFloat: result = $v.floatVal
  of ckString: result = v.strVal
  of ckKeyword: result = ":" & v.kwName
  of ckSymbol: result = v.symName
  of ckList:
    var parts: seq[string] = @[]
    for item in v.items: parts.add(cljReprLocal(item))
    result = "(" & parts.join(" ") & ")"
  of ckVector:
    var parts: seq[string] = @[]
    for item in v.items: parts.add(cljReprLocal(item))
    result = "[" & parts.join(" ") & "]"
  of ckMap:
    var parts: seq[string] = @[]
    for i in 0..<v.mapKeys.len:
      parts.add(cljReprLocal(v.mapKeys[i]) & " " & cljReprLocal(v.mapVals[i]))
    result = "{" & parts.join(", ") & "}"
  of ckSet:
    var parts: seq[string] = @[]
    for item in v.setItems: parts.add(cljReprLocal(item))
    result = "#{" & parts.join(" ") & "}"
  of ckFn: result = "#<fn:" & v.fnName & ">"
  of ckAtom: result = "(atom " & cljReprLocal(v.atomVal) & ")"
  of ckTransient: result = "#<transient>"
  of ckAgent: result = "(agent " & cljReprLocal(v.agentVal) & ")"

proc buildProgram(state: ReplState, form: CljVal, isDef: bool): string =
  var allForms = state.defs
  if isDef:
    allForms.add(form)

  var header = @[
    "# Generated by Bara Lang REPL",
    "import cljnim_runtime",
    "",
  ]

  var mainCode = ""
  if not isDef:
    mainCode = emitter.emitExpr(form, 0)

  var lines = header
  for d in allForms:
    lines.add(emitter.emitExpr(d, 0))

  if not isDef and mainCode.len > 0:
    lines.add("")
    lines.add("when isMainModule:")
    let stripped = mainCode.strip()
    if stripped.startsWith("echo ") or stripped.startsWith("discard ") or stripped.startsWith("block:"):
      lines.add("  " & stripped)
    else:
      lines.add("  echo cljRepr(" & stripped & ")")
  elif isDef:
    lines.add("")
    lines.add("when isMainModule:")
    lines.add("  discard nil")

  return lines.join("\n") & "\n"

proc compileAndRun(state: ReplState, nimCode: string): tuple[ok: bool, output: string, error: string] =
  let sourceFile = state.tempDir / "repl_input.nim"
  let binFile = state.tempDir / "repl_input"
  writeFile(sourceFile, nimCode)

  let compileCmd = "nim c --path:" & quoteShell(state.libPath) & " -o:" & binFile & " " & sourceFile
  let (compileOut, compileExit) = execCmdEx(compileCmd)

  if compileExit != 0 or not fileExists(binFile):
    return (false, "", compileOut)

  let (runOut, runExit) = execCmdEx(binFile)
  if runExit != 0:
    return (false, "", runOut)
  return (true, runOut.strip(), "")

proc evalForm*(state: var ReplState, formStr: string): JsonNode =
  let startTime = epochTime()

  var parsed: CljVal
  try:
    parsed = reader.read(formStr)
  except ReaderError as e:
    return %*{
      "status": "error",
      "error": {
        "type": "reader/error",
        "message": e.msg,
        "form": formStr
      },
      "meta": {
        "ns": state.ns,
        "ms": (epochTime() - startTime) * 1000
      }
    }

  let isDef = parsed.kind == ckList and parsed.items.len > 0 and
              parsed.items[0].kind == ckSymbol and
              parsed.items[0].symName in ["def", "defn"]

  # Macro-expand before evaluating
  let expanded = macroexpand(parsed)
  # Try in-memory evaluation first (fast path)
  let evalResult = evalAst(expanded, state.evalEnv)
  if evalResult.ok:
    let elapsed = (epochTime() - startTime) * 1000

    if evalResult.isDef:
      state.defs.add(parsed)
      return %*{
        "status": "ok",
        "result": {
          "type": "var",
          "name": evalResult.defName,
          "ns": state.ns,
          "printed": "#\"" & state.ns & "/" & evalResult.defName & "\""
        },
        "meta": {
          "ns": state.ns,
          "ms": elapsed,
          "form": formStr
        }
      }

    var printed: string
    if evalResult.value.kind == ckNil:
      printed = "nil"
    elif evalResult.value.kind == ckString:
      printed = evalResult.value.strVal
    else:
      printed = cljReprLocal(evalResult.value)

    return %*{
      "status": "ok",
      "result": {
        "type": "interpreted",
        "value": printed,
        "printed": printed
      },
      "meta": {
        "ns": state.ns,
        "ms": elapsed,
        "form": formStr
      }
    }

  # Fall back to compilation (slow path)
  let nimCode = buildProgram(state, parsed, isDef)
  let (ok, output, error) = compileAndRun(state, nimCode)

  let elapsed = (epochTime() - startTime) * 1000

  if not ok:
    var errObj = %*{
      "type": "compiler/error",
      "message": error,
      "form": formStr
    }
    if ai_assist.hasAiConfig():
      let aiRes = ai_assist.explainError(error, formStr, "REPL input")
      if aiRes.ok:
        errObj["ai_suggestion"] = %aiRes.suggestion
    return %*{
      "status": "error",
      "error": errObj,
      "meta": {
        "ns": state.ns,
        "ms": elapsed
      }
    }

  if isDef:
    state.defs.add(parsed)
    let name = if parsed.items[1].kind == ckSymbol: parsed.items[1].symName else: "unknown"
    return %*{
      "status": "ok",
      "result": {
        "type": "var",
        "name": name,
        "ns": state.ns,
        "printed": "#\"" & state.ns & "/" & name & "\""
      },
      "meta": {
        "ns": state.ns,
        "ms": elapsed,
        "form": formStr
      }
    }

  return %*{
    "status": "ok",
    "result": {
      "type": "compiled",
      "value": output,
      "printed": output
    },
    "meta": {
      "ns": state.ns,
      "ms": elapsed,
      "form": formStr
    }
  }

proc runHumanRepl*(state: var ReplState) =
  echo "Bara Lang REPL"
  echo "Type :quit to exit, :help for commands"
  echo ""

  while true:
    stdout.write(state.ns & "> ")
    stdout.flushFile()
    let line = stdin.readLine()

    if line.strip().len == 0:
      continue

    let cmd = line.strip()

    case cmd
    of ":quit", ":q":
      echo "Bye!"
      break
    of ":help", ":h":
      echo ":quit, :q    Exit REPL"
      echo ":defs        List defined vars"
      echo ":clear       Clear all definitions"
      echo ":ns          Show current namespace"
      echo ":ai <desc>   Ask AI to generate Bara Lang code"
      echo ":optimize <code>  Ask AI to suggest optimizations"
      echo ":debug <expr>     Ask AI to debug an expression"
    of ":defs":
      for d in state.defs:
        if d.kind == ckList and d.items.len > 1 and d.items[1].kind == ckSymbol:
          echo "  " & d.items[1].symName
    of ":clear":
      state.defs = @[]
      echo "Definitions cleared."
    of ":ns":
      echo state.ns
    else:
      if cmd.startsWith(":ai "):
        let description = cmd[4..^1].strip()
        if description.len == 0:
          echo "Usage: :ai <description>"
        elif not ai_assist.hasAiConfig():
          echo "No AI API key configured. Set DEEPSEEK_API_KEY, OPENAI_API_KEY, or MIMO_API_KEY."
        else:
          echo "🤖 Thinking..."
          let aiRes = ai_assist.generateCode(description)
          echo ai_assist.formatSuggestion(aiRes)
      elif cmd.startsWith(":optimize "):
        let code = cmd[10..^1].strip()
        if code.len == 0:
          echo "Usage: :optimize <code>"
        elif not ai_assist.hasAiConfig():
          echo "No AI API key configured."
        else:
          echo "🤖 Analyzing for optimizations..."
          let aiRes = ai_assist.optimizeCode(code)
          echo ai_assist.formatSuggestion(aiRes)
      elif cmd.startsWith(":debug "):
        let expr = cmd[7..^1].strip()
        if expr.len == 0:
          echo "Usage: :debug <expression>"
        elif not ai_assist.hasAiConfig():
          echo "No AI API key configured."
        else:
          echo "🤖 Debugging..."
          var evalRes: CljVal
          try:
            let res = eval.eval(expr, state.evalEnv)
            if not res.ok:
              evalRes = cljString("Error: " & res.error)
            else:
              evalRes = res.value
          except CatchableError as e:
            evalRes = cljString("Error: " & e.msg)
          let resultStr = if evalRes.kind == ckString: evalRes.strVal else: cljReprLocal(evalRes)
          let aiRes = ai_assist.debugCode(expr, resultStr)
          echo ai_assist.formatSuggestion(aiRes)
      else:
        let res = evalForm(state, cmd)
        if res["status"].getStr() == "ok":
          echo "=> " & res["result"]["printed"].getStr()
        else:
          echo "Error: " & res["error"]["message"].getStr()
          if res["error"].hasKey("ai_suggestion"):
            echo ""
            echo ai_assist.formatSuggestion(AiResponse(ok: true, suggestion: res["error"]["ai_suggestion"].getStr("")))

proc runJsonRepl*(state: var ReplState) =
  var readyMsg = %*{ "status": "ready", "ns": state.ns, "mode": "json" }
  echo $readyMsg
  stdout.flushFile()

  while true:
    let line = stdin.readLine()
    if line.strip().len == 0:
      continue

    var req: JsonNode
    try:
      req = parseJson(line)
    except JsonParsingError as e:
      var err = %*{
        "status": "error",
        "error": { "type": "json/parse-error", "message": e.msg }
      }
      echo $err
      stdout.flushFile()
      continue

    var op = req.getOrDefault("op").getStr("")

    # Tool-call format: {"tool":"cljnim/eval","args":{"form":"..."}}
    if req.hasKey("tool"):
      let tool = req["tool"].getStr("")
      if tool == "cljnim/eval":
        let args = req.getOrDefault("args")
        if args.kind == JObject and args.hasKey("form"):
          let form = args["form"].getStr("")
          if form.len > 0:
            let res = evalForm(state, form)
            if req.hasKey("request-id"):
              res["request-id"] = req["request-id"]
            res["tool"] = %tool
            echo $res
            stdout.flushFile()
            continue
      var err = %*{
        "status": "error",
        "error": { "type": "repl/invalid-tool-call", "message": "Invalid tool call: " & tool }
      }
      echo $err
      stdout.flushFile()
      continue

    if op.len == 0: op = "eval"

    case op
    of "eval":
      let form = req.getOrDefault("form").getStr("")
      if form.len == 0:
        var err = %*{
          "status": "error",
          "error": { "type": "repl/missing-form", "message": "Missing :form field" }
        }
        echo $err
      else:
        let res = evalForm(state, form)
        if req.hasKey("request-id"):
          res["request-id"] = req["request-id"]
        echo $res

    of "eval-batch":
      let forms = req.getOrDefault("forms")
      var results: seq[JsonNode] = @[]
      if forms.kind == JArray:
        for f in forms:
          let formStr = f.getStr("")
          if formStr.len > 0:
            results.add(evalForm(state, formStr))
      var batchRes = %*{ "status": "ok", "results": results }
      echo $batchRes

    of "get-defs":
      var defs: seq[string] = @[]
      for d in state.defs:
        if d.kind == ckList and d.items.len > 1 and d.items[1].kind == ckSymbol:
          defs.add(d.items[1].symName)
      var defsRes = %*{ "status": "ok", "defs": defs, "ns": state.ns }
      echo $defsRes

    of "clear":
      state.defs = @[]
      var clearRes = %*{ "status": "ok", "cleared": true }
      echo $clearRes

    of "ai-generate":
      let description = req.getOrDefault("description").getStr("")
      if description.len == 0:
        echo $(%*{ "status": "error", "error": { "type": "repl/missing-description", "message": "Missing :description field" } })
      elif not ai_assist.hasAiConfig():
        echo $(%*{ "status": "error", "error": { "type": "repl/no-ai-config", "message": "No AI API key configured" } })
      else:
        let aiRes = ai_assist.generateCode(description)
        if aiRes.ok:
          echo $(%*{ "status": "ok", "code": %aiRes.suggestion })
        else:
          echo $(%*{ "status": "error", "error": { "type": "repl/ai-error", "message": %aiRes.suggestion } })

    of "ai-optimize":
      let code = req.getOrDefault("code").getStr("")
      if code.len == 0:
        echo $(%*{ "status": "error", "error": { "type": "repl/missing-code", "message": "Missing :code field" } })
      elif not ai_assist.hasAiConfig():
        echo $(%*{ "status": "error", "error": { "type": "repl/no-ai-config", "message": "No AI API key configured" } })
      else:
        let aiRes = ai_assist.optimizeCode(code)
        if aiRes.ok:
          echo $(%*{ "status": "ok", "suggestion": %aiRes.suggestion })
        else:
          echo $(%*{ "status": "error", "error": { "type": "repl/ai-error", "message": %aiRes.suggestion } })

    of "ai-debug":
      let expr = req.getOrDefault("expression").getStr("")
      if expr.len == 0:
        echo $(%*{ "status": "error", "error": { "type": "repl/missing-expression", "message": "Missing :expression field" } })
      elif not ai_assist.hasAiConfig():
        echo $(%*{ "status": "error", "error": { "type": "repl/no-ai-config", "message": "No AI API key configured" } })
      else:
        var resultStr = ""
        try:
          let evalRes = eval.eval(expr, state.evalEnv)
          resultStr = if evalRes.ok: cljReprLocal(evalRes.value) else: "Error: " & evalRes.error
        except CatchableError as e:
          resultStr = "Error: " & e.msg
        let aiRes = ai_assist.debugCode(expr, resultStr)
        if aiRes.ok:
          echo $(%*{ "status": "ok", "analysis": %aiRes.suggestion, "result": %resultStr })
        else:
          echo $(%*{ "status": "error", "error": { "type": "repl/ai-error", "message": %aiRes.suggestion } })

    of "quit":
      var quitRes = %*{ "status": "ok", "bye": true }
      echo $quitRes
      stdout.flushFile()
      break

    else:
      var unkRes = %*{
        "status": "error",
        "error": { "type": "repl/unknown-op", "message": "Unknown op: " & op }
      }
      echo $unkRes

    stdout.flushFile()

proc handleClient(state: var ReplState, client: Socket) =
  var readyMsg = $(%*{ "status": "ready", "ns": state.ns, "mode": "nrepl" }) & "\n"
  client.send(readyMsg)

  while true:
    try:
      var line = ""
      client.readLine(line)
      if line.len == 0:
        break
      let req = parseJson(line)
      let op = req.getOrDefault("op").getStr("eval")
      case op
      of "eval":
        let form = req.getOrDefault("form").getStr("")
        if form.len > 0:
          let res = evalForm(state, form)
          client.send($res & "\n")
      of "get-defs":
        var defs: seq[string] = @[]
        for d in state.defs:
          if d.kind == ckList and d.items.len > 1 and d.items[1].kind == ckSymbol:
            defs.add(d.items[1].symName)
        var defsRes = %*{ "status": "ok", "defs": defs, "ns": state.ns }
        client.send($defsRes & "\n")
      of "clear":
        state.defs = @[]
        client.send($(%*{ "status": "ok", "cleared": true }) & "\n")
      of "quit":
        client.send($(%*{ "status": "ok", "bye": true }) & "\n")
        break
      else:
        client.send($(%*{ "status": "error", "error": { "type": "repl/unknown-op", "message": "Unknown op: " & op } }) & "\n")
    except EOFError:
      break
    except CatchableError as e:
      client.send($(%*{ "status": "error", "error": { "type": "repl/protocol-error", "message": e.msg } }) & "\n")
      break
    except ValueError as e:
      client.send($(%*{ "status": "error", "error": { "type": "repl/parse-error", "message": e.msg } }) & "\n")
      break
    except OSError as e:
      client.send($(%*{ "status": "error", "error": { "type": "repl/io-error", "message": e.msg } }) & "\n")
      break
  client.close()

proc runTcpRepl*(state: var ReplState, port: int) =
  var server = newSocket()
  server.setSockOpt(OptReuseAddr, true)
  server.bindAddr(Port(port))
  server.listen()
  stderr.writeLine("nREPL listening on port " & $port)

  while true:
    var client = newSocket()
    server.accept(client)
    stderr.writeLine("Client connected")
    var clientState = state  # copy
    handleClient(clientState, client)
