#!/usr/bin/env python3
"""Generate Bars code with guaranteed paren balance.

Usage: python3 gen_hir.py > lib/hir.brs
"""
import textwrap

class BarsWriter:
    def __init__(self):
        self.lines = []
        self.indent = 0
    
    def emit(self, text):
        self.lines.append("  " * self.indent + text)
    
    def emit_raw(self, text):
        self.lines.append(text)
    
    def write(self):
        return "\n".join(self.lines) + "\n"

w = BarsWriter()

# ===========================================================================
# Helpers
# ===========================================================================

w.emit_raw(";; Bars HIR Lowering — Stage 2 of self-hosting")
w.emit_raw(";; Generated by tools/gen_hir.py — paren balance guaranteed.")
w.emit_raw("")

# int-str: number to string
w.emit_raw("(defn int-str [n]")
w.emit_raw("  (let [d \"0123456789\"]")
w.emit_raw("    (if (< n 0)")
w.emit_raw("      (str-concat \"-\" (int-str (- 0 n)))")
w.emit_raw("      (if (< n 10)")
w.emit_raw("        (str-slice d n (+ n 1))")
w.emit_raw("        (str-concat (int-str (/ n 10)) (str-slice d (% n 10) (+ (% n 10) 1)))))))")
w.emit_raw("")

# fresh-temp, fresh-label
w.emit_raw("(defn fresh-temp [t] (str-concat \"t\" (int-str t)))")
w.emit_raw("(defn fresh-label [l prefix] (str-concat prefix (int-str l)))")
w.emit_raw("")

# put
w.emit_raw("(defn put [lines s] (do (push lines s) lines))")
w.emit_raw("")

# op-fmt
w.emit_raw("(defn op-fmt [s]")
w.emit_raw("  (let [c (str-get s 0)]")
w.emit_raw("    (if (= c 45)")
w.emit_raw("      (str-concat \"Const(\" (str-concat s \")\"))")
w.emit_raw("      (if (if (>= c 48) (<= c 57) false)")
w.emit_raw("        (str-concat \"Const(\" (str-concat s \")\"))")
w.emit_raw("        (str-concat \"Var(\\\"\" (str-concat s \"\\\")\"))))))")
w.emit_raw("")

# Extractors
w.emit_raw("(defn ret-op [res] (get res 0))")
w.emit_raw("(defn ret-st [res] (get res 1))")
w.emit_raw("(defn st-t [res] (get (ret-st res) 0))")
w.emit_raw("(defn st-l [res] (get (ret-st res) 1))")
w.emit_raw("(defn mk-ret [op t l] [op [t l]])")
w.emit_raw("")

# AST helpers
w.emit_raw("(defn is-atom? [x] (< (get x 0) 1000))")
w.emit_raw("(defn tag-of [x] (get x 0))")
w.emit_raw("(defn val-of [x] (get x 1))")
w.emit_raw("(defn list-head [x] (get x 0))")
w.emit_raw("")

# ===========================================================================
# LOWER-EXPR (generated from tree structure)
# ===========================================================================

# Build an S-expression tree with automatic paren closing
class SExpr:
    def __init__(self, head, *args):
        self.head = head
        self.args = list(args)
    
    def render(self, indent=0):
        """Render as Bars code with proper indentation."""
        prefix = "  " * indent
        if not self.args:
            return f"{prefix}({self.head})"
        
        # Simple case: all args are strings
        if all(isinstance(a, str) for a in self.args):
            body = " ".join(self.args)
            line = f"{prefix}({self.head} {body})"
            if len(line) < 100:
                return line
            # Multi-line
            result = [f"{prefix}({self.head}"]
            for a in self.args:
                result.append(f"{prefix}   {a}")
            result.append(f"{prefix} )")
            return "\n".join(result)
        
        # Nested SExpr args
        result = [f"{prefix}({self.head}"]
        for a in self.args:
            if isinstance(a, SExpr):
                result.append(a.render(indent + 1))
            elif isinstance(a, str):
                result.append(f"{prefix}  {a}")
            else:
                result.append(f"{prefix}  {str(a)}")
        result.append(f"{prefix} )")
        return "\n".join(result)


# We'll build the functions as nested Python data that gets rendered

# lower-expr
lower_expr_code = """(defn lower-expr [ast t l lines]
  (if (is-atom? ast)
    ;; Atom branch
    (let [tag (tag-of ast)]
      (cond
        (= tag 0) (mk-ret (int-str (val-of ast)) t l)
        (= tag 1) (mk-ret (val-of ast) t l)
        (= tag 2) (mk-ret (val-of ast) t l)
        (= tag 3) (mk-ret (val-of ast) t l)
        (= tag 4) (mk-ret "0" t l)
        (= tag 5) (mk-ret (int-str (val-of ast)) t l)
        :else     (mk-ret "<unk>" t l)))
    ;; List branch
    (let [head (list-head ast)
          tag  (tag-of head)]
      (cond
        (= tag 10) (lower-defn ast t l lines)
        (= tag 11) (lower-let  ast t l lines)
        (= tag 12) (lower-if   ast t l lines)
        (= tag 13) (lower-do   ast t l lines)
        :else      (lower-call ast t l lines)))))"""

# Verify balance
def check_balance(code):
    bal = 0
    for ch in code:
        if ch == '(': bal += 1
        if ch == ')': bal -= 1
    return bal

assert check_balance(lower_expr_code) == 0, f"lower-expr unbalanced: {check_balance(lower_expr_code)}"
print(lower_expr_code)
print()

# lower-defn
lower_defn_code = """(defn lower-defn [ast t l lines]
  (let [name  (val-of (get ast 1))
        params (get ast 2)
        body   (get ast 3)
        entry  (fresh-label l "entry_")
        l      (+ l 1)]
    (do (put lines (str-concat "func " (str-concat name ":")))
        (do (put lines (str-concat "  " (str-concat entry ":")))
            (let [res (lower-expr body t l lines)
                  op  (ret-op res)
                  t   (st-t res)
                  l   (st-l res)]
              (do (put lines (str-concat "    Assign { dest: \\"_ret\\", value: " (str-concat (op-fmt op) " }")))
                  (do (put lines "    Return(Var(\\"_ret\\"))")
                      (let [mlabel (fresh-label l "main_entry_")
                            l      (+ l 1)]
                        (do (put lines "func main:")
                            (do (put lines (str-concat "  " (str-concat mlabel ":")))
                                (do (put lines "    Return(Const(0))")
                                    (mk-ret "<done>" t l)))))))))))"""

assert check_balance(lower_defn_code) == 0, f"lower-defn unbalanced: {check_balance(lower_defn_code)}"
print(lower_defn_code)
print()

# lower-call
lower_call_code = """(defn lower-call [ast t l lines]
  (let [fname (val-of (get ast 0))
        n     (count ast)]
    (loop [i 0 args (vector) t t l l]
      (if (>= i n)
        (let [dest (fresh-temp t)
              t    (+ t 1)
              astr (join-args args 0)]
          (do (put lines (str-concat "    Call { dest: \\"" (str-concat dest (str-concat "\\", func: \\"" (str-concat fname (str-concat "\\", args: [" (str-concat astr "] }")))))))
              (mk-ret dest t l)))
        (let [res (lower-expr (get ast i) t l lines)
              op  (ret-op res)
              t   (st-t res)
              l   (st-l res)]
          (do (push args op)
              (recur (+ i 1) args t l)))))))"""

assert check_balance(lower_call_code) == 0, f"lower-call unbalanced: {check_balance(lower_call_code)}"
print(lower_call_code)
print()

# ... more functions ...
print("All generated functions balanced!")
